/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic SETSTUDIO(R) 9.3.0   2020-06-18

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include <stddef.h>
#include "stm32f2xx.h"

#include <stdbool.h>
#include "extern.h"
#include "system.h"
#ifdef USE_I2C_EEPROM
#include "eeprom.h"
#endif /* USE_I2C_EEPROM */
#include "diagnostic.h"
#include "can.h"
#include "serial.h"
#include "motor.h"
#include "timer.h"
#include "calibration.h"
#include "misc.h"
#include "misc1.h"
#include "Emergency.h"

/* New architecture modules */
#include "shared_vars.h"
#include "safety.h"
#include "debug_log.h"
#include "motor_ctrl.h"
#include "isr_new.h"


/* Private typedef */
/* Private define  */
#ifdef USE_STM322xG_EVAL
  #define MESSAGE1   "  High-performance  "
  #define MESSAGE2   "    STM32 F-2       "
  #define MESSAGE3   "    running on      "
  #define MESSAGE4   "   STM3220F-EVAL    "
#endif
  #define MESSAGE5   " program built with "
  #define MESSAGE6   " Atollic SETSTUDIO "

/* Private macro */
/* Private variables */
 USART_InitTypeDef USART_InitStructure;

#define	UART_MEMBRANELIVE_Signal_send				"[SP_MEMB_SIGN_]"

 /* CurCaptureMode and aging-mode variables moved to system.c (see shared_vars.h) */

 TIM_TimeBaseInitTypeDef 			TIM_TimeBaseStructure;
 TIM_OCInitTypeDef					TIM_OCInitStructure;


/* Private function prototypes */
/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main(void)
{
    bool bGenCheck, bCollCheck, bMotCheck;

    System_Init();

    /* Initialize new architecture modules (after all peripheral init) */
    DbgLog_Init();
    MotorCtrl_Init();
    Safety_IWDG_Init();

    printUart(DBG_MSG_PC, "System configuration is complete");
	
    if((sysInfo.nFW_Com_Value & 0x0001) == 0x0000)
		EEPRom_Load_Apply_minus_Offset();
	else
		EEPRom_Load_Align_Offset();

	if(EMG_ProcessSwitch())
	{
		printUart(DBG_MSG_PC, "=============Generator Check=============");

	    bGenCheck = SysInitGenerator();
	    if (!bGenCheck)
	        printUart(DBG_MSG_PC, "Boot Condition : Generator error");
		printUart(DBG_MSG_PC, "======================================");
		printUart(DBG_MSG_PC, "=============Collimator Check=============");

	    bCollCheck = SysInitCollimator();
	    if (!bCollCheck)
	        printUart(DBG_MSG_PC, "Boot Condition : Collimator error");

		printUart(DBG_MSG_PC, "======================================");
	    bMotCheck = Motor_Init_Check();
	    if (!bMotCheck)
	        printUart(DBG_MSG_PC, "Boot Condition : Motor error");
	}
	else
	{
		bGenCheck=RESET;
		bCollCheck=RESET;
		bMotCheck=RESET;
	}    

	if (bGenCheck && bCollCheck && bMotCheck)
	{		
        printUart(DBG_MSG_PC, "[SP_BOOT_DONE_]");
		gMachStat.bBootDone = SET;
	}
	else
	{
		printUart(DBG_MSG_PC, "[SP_BOOT_FAIL_]");
        gMachStat.bBootErr = SET;
    }	
	
#ifdef USE_TABLET_PC
	UART_SendMessage(DBG_MSG_TABLET, UART_MEMBRANELIVE_Signal_send);
#endif /* USE_TABLET_PC */
	IntTimer_Delay(600);
	while(!IntTimer_GetStatus());

	CtParam.bFirstCT=RESET;
	PanoParam.bFirstPano=RESET;

	UART_Memb_Init_Data();

    while(1)
	{
		switch(CurCaptureMode)
		{
		case CAPTURE_PANO:
            PanoCapture();
			break;

		case CAPTURE_CT:
			CtCapture();
			break;

		case CAPTURE_SCAN:
            if (sysInfo.model_id == MODEL_T2_CS)
			{
                ScanCapture();
            }
			else
			{
                printUart(DBG_MSG_PC, "can't not support cephalo");
                CurCaptureMode = CAPTURE_CANCEL;
            }
			break;

		case CALIBRATION_MODE:
            CalibrationMode();
			break;

		case GEOMETRY_ALIGN_MODE:
            GeometryAlignMode();
			break;
#ifdef USE_I2C_EEPROM
		case EEPROM_MODE:
			EEPRom_ModeLoop();
			break;
#endif /* USE_I2C_EEPROM */
		case DIAGNOSTIC_MODE:
			DiagnosticMode();
			break;

		case RESET_MODE:
			// 20200729 -- jehun
			// pano에서 emg 스위치 누른 후 ct로 진행하면 pano에 beam이 안꺼지는 현상 개선
			LaserControl(TYPE_HEAD_CEPH, RESET);
			LaserControl(TYPE_HEAD_PANO, RESET);
			LaserControl(TYPE_FOOT, RESET);
			Exposure_CtrlLed(EXPOSURE_LED_GPIO_DISABLE);
			UART_SendMessage(DBG_MSG_PC, "[SP_MODE_RESET]");
#ifdef USE_TABLET_PC
			UART_SendMessage(DBG_MSG_TABLET, "[SP_MODE_RESET]");
#endif /* USE_TABLET_PC */			
			
			if ( (sysInfo.model_id == MODEL_T2_CS) && (g_bTiltStatus == SET) )
			{
				if (!CAN_Collimator_SendMessage(CMD_TILT_OFF, 0, 0, 5000, 2))
				{
					printUart(DBG_MSG_PC, "Titing Error");
				}
				g_bTiltStatus = RESET;
			}

			Motor_MoveInitPosition();
#ifdef USE_TABLET_PC
			UART_SendMessage(DBG_MSG_TABLET, "[SP_CAPT_CANCE]");
#endif /* USE_TABLET_PC */

			CurCaptureMode = CAPTURE_CANCEL;
			break;

		case CAPTURE_CANCEL:
		default:
			if(!bGenCheck || !bCollCheck || !bMotCheck)
			{
				//200131 HWAN  lamp start signal need.
				//while(!LampTimer_GetStatus());
				//LampErrorTimer_Enable(4,4);


				if(!bMotCheck)
				{
					while(!LampTimer_GetStatus());
					Motor_Lamp_ErrorStatus();
				}

				if(!bGenCheck)
				{
					while(!LampTimer_GetStatus());
					LampErrorTimer_Enable(4,10);
					while(!LampTimer_GetStatus());
					LampErrorTimer_Enable(5,10);
					while(!LampTimer_GetStatus());
					LampErrorTimer_Enable(4,10);
					while(!LampTimer_GetStatus());
					LampErrorTimer_Enable(5,10);
					while(!LampTimer_GetStatus());
					LampErrorTimer_Enable(0,10);
					while(!LampTimer_GetStatus());	
					LampErrorTimer_Enable(5,2);
				}

				if(!bCollCheck)
				{
					while(!LampTimer_GetStatus());
					LampErrorTimer_Enable(4,10);
					while(!LampTimer_GetStatus());
					LampErrorTimer_Enable(5,10);
					while(!LampTimer_GetStatus());
					LampErrorTimer_Enable(0,10);
					while(!LampTimer_GetStatus());	
					LampErrorTimer_Enable(5,2);
				}

			}
            else if (IntTimer.bLampEnable == SET)
			{
            	// jehun -  20200812
            	// mode cancel 후 조사 스위치 LED OFF 안돼는 현상 수정
            	Exposure_CtrlLed(EXPOSURE_LED_GPIO_DISABLE);

            	while(!LampTimer_GetStatus());
            }

#ifdef USE_AGING_MODE
#define AGING_INTERVAL_TIME			30000  //��� �ð� : 30Sec
			if ( (g_bAgingMode == SET) && (PrevCaptureMode != CAPTURE_CANCEL) )
			{
				if (PrevCaptureMode == CAPTURE_PANO)
				{
					CurCaptureMode = CAPTURE_CT;
				}
				else if (PrevCaptureMode == CAPTURE_CT)
				{
					CurCaptureMode = CAPTURE_SCAN;
				}
				else if (PrevCaptureMode == CAPTURE_SCAN)
				{
					Column_Control(COLUMN_DOWN);

					IntTimer_Delay(AGING_INTERVAL_TIME);
					while(!IntTimer_GetStatus());

					Column_Control(COLUMN_STOP);

					Column_Control(COLUMN_UP);

					IntTimer_Delay(AGING_INTERVAL_TIME);
					while(!IntTimer_GetStatus());

					Column_Control(COLUMN_STOP);
					

					if (g_bAgingMode == SET)
					{
						CurCaptureMode = CAPTURE_PANO;
					}
				}
			}
#endif /* USE_AGING_MODE */
			break;
		}

		/* CAN message processing (flag set by CAN2_RX0_IRQHandler in isr_new.c).
		 * Copy ISR buffer to legacy CAN_RxMessage under IRQ disable to prevent
		 * a second CAN frame from overwriting during processing. */
		if (g_can_rx_flag) {
			__disable_irq();
			CAN_RxMessage = g_can_rx_msg;
			g_can_rx_flag = 0;
			__enable_irq();
			CAN_ParseMessage();
		}

		/* Safety checks and debug log flush every main loop iteration */
		Safety_CheckMainLoop();
		DbgLog_Flush();
    }
}

#ifdef  USE_FULL_ASSERT

/**
  * @brief  Reports the name of the source file and the source line number
  *   where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t* file, uint32_t line)
{
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */

  /* Infinite loop */
  while (1)
  {
  }
}
#endif

/*
 * Minimal __assert_func used by the assert() macro
 * */
void __assert_func(const char *file, int line, const char *func, const char *failedexpr)
{
  while(1)
  {}
}

/*
 * Minimal __assert() uses __assert__func()
 * */
void __assert(const char *file, int line, const char *failedexpr)
{
   __assert_func (file, line, NULL, failedexpr);
}

#ifdef USE_SEE
#ifndef USE_DEFAULT_TIMEOUT_CALLBACK
/**
  * @brief  Basic management of the timeout situation.
  * @param  None.
  * @retval sEE_FAIL.
  */
uint32_t sEE_TIMEOUT_UserCallback(void)
{
  /* Return with error code */
  return sEE_FAIL;
}
#endif
#endif /* USE_SEE */

#ifdef USE_EVAL_AUDIO
/**
  * @brief  Basic management of the timeout situation.
  * @param  None.
  * @retval sEE_FAIL.
  */
void EVAL_AUDIO_TransferComplete_CallBack(uint32_t pBuffer, uint32_t Size)

{
  /* TODO, implement your code here */
  return;
}
#endif /* USE_EVAL_AUDIO */

